import os
import sys

#Import the path from the user's environment
env = Environment(ENV = {'PATH' : os.environ['PATH']})

#Attempt to fix the path if the user is on windows and the path
# doesn't contain kernel32.lib
extra_libs = []
if env['PLATFORM'] == 'win32':
   extra_libs = ['C:\\Program Files\\Microsoft SDKs\\Windows\\v6.0A\\Lib']
   env['ENV']['TMP'] = os.environ['TMP'] 
   
#Prevent Windows users from messing up their directory structure; hide the "install" alias from them.
if env['PLATFORM'] != 'win32':
   env.Alias('install', '/usr/lib/waitzar')


#Sources
sources = Split("""
   fontconv.cpp
   fontmap.cpp
   lib.cpp
   regex.cpp
   WordBuilder.cpp
   SentenceList.cpp
   """)
sources = map(lambda x:os.path.join("waitzar",x), sources)


#Build the shared library
wz_shared = env.SharedLibrary('waitzar', sources, LIBPATH = extra_libs)

#Install it
env.Install('/usr/lib/waitzar', wz_shared)







